// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoList.DataContext;

#nullable disable

namespace ToDoList.Migrations
{
    [DbContext(typeof(Connection))]
    [Migration("20240604153438_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("ToDoList.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("category");
                });

            modelBuilder.Entity("ToDoList.Model.Tugas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Category_ID")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Category_ID");

                    b.HasIndex("Deskripsi")
                        .IsUnique();

                    b.ToTable("tugas");
                });

            modelBuilder.Entity("ToDoList.Model.Tugas", b =>
                {
                    b.HasOne("ToDoList.Model.Category", "Category_FK")
                        .WithMany("Tugas")
                        .HasForeignKey("Category_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category_FK");
                });

            modelBuilder.Entity("ToDoList.Model.Category", b =>
                {
                    b.Navigation("Tugas");
                });
#pragma warning restore 612, 618
        }
    }
}
